### ISSUE TITLE
Bug: Cli cannot detect already installed flavours if not on the first position in flavours.yaml file. 

### ISSUE THREAD

**Issue by spookyintheam** [catppuccin/cli#13]
**Description of the issue**
- The cli cannot detect when the user reinstalls the same flavour again but its position is not first in `flavours.yaml` file. 

**Current  behaviour**
If the contents of the `flavours.yaml` file is: 
```yaml
app_name: helix
installed_flavour:
    flavour: mocha
app_name: helix
installed_flavour:
    flavour: latte
```
and if the user tries to reinstall the latte variant, it should throw an error since latte is installed already but it instead throws the error:
```bash
Error: yaml: unmarshal errors:
  line 4: mapping key "app_name" already defined at line 1
  line 7: mapping key "app_name" already defined at line 1
  line 5: mapping key "installed_flavour" already defined at line 2
  line 8: mapping key "installed_flavour" already defined at line 2
--- snipped ---
```

**Expected behaviour**
The cli should detect that the latte variant is already installed and instead throw the error:
```bash
Flavour latte already exists for helix
exit status 1
```

A good start approach in solving this would be to understandthe `MakeFlavour` function: 
https://github.com/catppuccin/cli/blob/b0a050535705e70f2493606fc8dd382ff87ae088/internal/utils/utils.go#L406 

**Acceptance criteria**
Any changes should be made on the dev branch and the PRs should be opened against the dev branch itself.

**Comment by DakshG07** [comment]
#27 takes care of this. Closing.
