### ISSUE TITLE
Suggestion: Save location instead of flavour name for easier uninstallation. 

### ISSUE THREAD

**Issue by spookyintheam** [catppuccin/cli#14]
**This is more of a suggestion, not a bug**

### An alternate implementation idea for saving flavours during install 
Currently, the half-working implementation saves the flavour the user enters and saves it to a file `flavours.yaml` at `$XDG_DATA_HOME/catppuccin-cli/`. This is a bit problematic since this also causes #13. An alternate way to tackle this was suggested by @DakshG07, where we can store the location where a new config is being installed and then this location can be used during installation.

**Comment by DakshG07** [comment]
Yeah, we’ve implemented this now in #27. Closing.
