### ISSUE TITLE
Bug: Remove function removing wrong files

### ISSUE THREAD

**Issue by spookyintheam** [catppuccin/cli#15]
**Description**
The remove function needs a rewrite and as it currently stands, it does not yet handle flavours. But the function removes the top-level directory for most applications which is intended but this can cause issues with some electron based applications which store their user configuration in these top-level Directories (example: [catppuccin/joplin](https://github.com/catppuccin/joplin) or [catppuccin/element](https://github.com/catppuccin/element)). 
Invoking the remove command for such apps also removes the user configuration and usually logs the user out. This needs to be tackled. 

**Possible approach**
This can be worked in tandem with #14 by saving the installation location of the config for an application and then reading this installed location to uninstall only the required files, thus not removing the top-level directory.

**Comment by DakshG07** [comment]
#27 fixes this. Closing.
