### ISSUE TITLE
Unclear error message when initializing a duplicate project

### ISSUE THREAD

**Issue by bashbunni** [catppuccin/cli#18]
**Describe the bug**
When you try to create a new project with a name that conflict with an existing project, the error message is too vague to help debug. 

**Expected behavior**
I believe the error message should state that a project with the name ____ already exists in *insert location*

**Screenshots**
![error message](https://user-images.githubusercontent.com/15822994/195968939-bb9fe16b-9a02-4bd5-9aab-95e8b39f41f6.png)

**Device Information**
MacOS Monterey
go version go1.19 darwin/arm64

**Comment by spookyintheam** [comment]
Thanks for bringing this to attention! This should be pretty easy to fix.

**Comment by bashbunni** [comment]
on it :glassescat

**Comment by spookyintheam** [comment]
Fixed with #20. Thanks for your PR!
