### ISSUE TITLE
Why are we cloning repos to pwd?

### ISSUE THREAD

**Issue by bashbunni** [catppuccin/cli#19]
Wouldn't cloning repos to the pwd make it harder to check if something is already installed?
If we're installing themes, are we installing them to a particular directory depending on the project?
So, for example kitty themes we would want to install it at `~/.config/kitty/themes/` or something. Would it be worth having some confirmation of the default install location and you can provide an alternate location if you want?

**Comment by DakshG07** [comment]
Never thought of the confirmation before...we could do that!

**Comment by bashbunni** [comment]
Is this what you're already doing for the `new` command where you set the install locations? :eyes:

**Comment by DakshG07** [comment]
To an extent; it's really just used to fill in the `.catppuccin.yaml`.

**Comment by DakshG07** [comment]
Solved; closing.
