### ISSUE TITLE
Fancy pants logger

### ISSUE THREAD

**Issue by jolheiser** [catppuccin/cli#24]
Maybe something like https://github.com/caarlos0/log with catppuccin styles?

**Comment by DakshG07** [comment]
I mean... it is quite the task. I would say no.

**Comment by jolheiser** [comment]
For the most part it's just replacing `fmt.Println` with `log.Info` or similar.
But it's up to you, it's just an aesthetic thing either way.

**Comment by DakshG07** [comment]
Oh, really? In that case, sure, let’s do it.
