### ISSUE TITLE
Rename package to ctp by changing locations

### ISSUE THREAD

**Issue by jolheiser** [catppuccin/cli#25]
Optional, but raising an issue since we spoke about it in Discord.

Perhaps the current `cmd` directory could be moved to `internal`, and we could move `main.go` to `cmd/ctp`

This would mean that building would no longer strictly require the `-o` flag, and `go install` would work out of the box.

**Comment by spookyintheam** [comment]
Yes this makes the building process cleaner. I'll add this to the README!

**Comment by jolheiser** [comment]
The other option is to rename the repo (and module) to `ctp`.

**Comment by DakshG07** [comment]
Hm. Would Cobra like this?

**Comment by jolheiser** [comment]
Cobra the library is agnostic.
Cobra the CLI tool is what jams everything into `cmd`.

**Comment by DakshG07** [comment]
Updated for clarity.

**Comment by DakshG07** [comment]
Any idea how we could implement this? I’m not familiar with how this works.

**Comment by jolheiser** [comment]
> Any idea how we could implement this? I’m not familiar with how this works.

Absolutely. I will open a draft PR when I have a chance to show a possible layout.

The tl;dr is that everything in `cmd` would be moved somewhere like `internal/cli` (example) and then `main.go` is moved to `cmd/ctp/main.go`
There would need to be some docs changes as well as goreleaser, but after that `go build cmd/ctp` and `go install github.com/catppuccin/cmd/ctp` would create a binary called `ctp` by default.

**Comment by jolheiser** [comment]
Resolved by #29
