### ISSUE TITLE
Install command attempts to install even when no arguments are passed

### ISSUE THREAD

**Issue by hsheikhali1** [catppuccin/cli#26]
**Describe the bug**
This is a trivial bug and more so a cleanup step then anything but when running `ctp install` without a specific input argument, the cli attempts to install rather than detect that there was no input and exit gracefully. 

**Observed behaviour**
The issue I've seen is as follows:

1. Install and build the cli.
2. run `./ctp install`
3. ctp attempts to install packages and attempts to check for installed packages but outputs nothing.

**Expected behavior**
ctp returns an error indicating that for the install com

**Screenshots**
<img width="988" alt="Screen Shot 2022-10-30 at 11 13 46 AM" src="https://user-images.githubusercontent.com/14851850/198886374-5c8a50cc-bf86-45e4-a645-070acb3de25d.png">
mand cannot have an empty arg.

**Device Information**
OS: MacOS

**Comment by hsheikhali1** [comment]
This can also be extended to include all instances where we are expecting a slice of inputs (install, remove etc)

for remove command:
```go
func removeInstalled(packages []string) {
	fmt.Println("Checking if the packages are installed...")

	// determine if there are packages in the packages slice
	if len(packages) == 0 {
		fmt.Println("No packages found to uninstall.")
		// gracefully exist the program if there are no packages
		os.Exit(0)
	}
    // rest of code ...
}
```

**Comment by DakshG07** [comment]
I was thinking perhaps no arguments could trigger a help dialog? Informing the user on how to use the command.

**Comment by hsheikhali1** [comment]
@DakshG07 I'm going to work on this issue :) Just commenting so y'all know

**Comment by DakshG07** [comment]
Alright, got that!

**Comment by jha-sk** [comment]
I've picked this up and will try to finish it soon.
