### ISSUE TITLE
Collaboration on working on an abstraction over the themability of applications

### ISSUE THREAD

**Issue by mainrs** [catppuccin/cli#46]
Hello!

I like the idea of a CLI that can be used to theme different applications the way you want. I was wondering if, instead of locking the CLI in to the catppuccin ecosystem, you would be interested in working together to create some kind of description format that can be used for any theme.

Let's call these files data files. These files would declare a set of inputs that they need in order to apply a given theme to an application. The data files then declare a set of steps necessary to apply a given theme to an application. This could include copying a given input file to a specific location on the file system, editing existing configuration files, running commands etc.

This CLI would then use these data files to apply the theme. The input files in this case would correspond to the already existing catppuccin repositories. One could even include a step that provides input files by cloning a given repository. 

I hope my idea is understandable. I have mocked the idea into an example JSON data file. 

Since the CLI already has to write custom logic to apply the theme correctly (see yaml files), I thought it might be worth to bring this to the next level and make it re-usable for others too.

Let me know if there is any interest in this.

**Comment by sgoudham** [comment]
Hey :wave: 

Sorry for the long wait!

We're currently re-evaluating what we want catppuccin/cli to actually do. We don't have any interest in trying to create a standard description format at this time but maybe it could be a possibility later down the road once the CLI fulfils the wants/needs of the Catppuccin organisation.

As a sidenote, you may be interested in [Nix](https://nixos.org/) and our [catppuccin/nix](https://github.com/catppuccin/nix) repository which largely resonates which your aim and goals outlined here!

Sorry again and thanks for taking the time to write out your idea!
