### ISSUE TITLE
Caching repos bug

### ISSUE THREAD

**Issue by ohxxm** [catppuccin/cli#5]
Error:
repos.json does not exist. Caching JSON...Received repositories. Caching! Cannot open file. 

This happens when trying to search a catppuccin port.

**Comment by ohxxm** [comment]
After a minute of researching, when running this under bash, it works and installs the port but under fish you get a seperate error:

Installing packages...
helix
https://raw.githubusercontent.com/catppuccin/helix/main/.catppuccin.yaml
helix does not have a .catppuccin.yaml
Checking for installed packages:

**Comment by DakshG07** [comment]
I’ve found the problem here.
You’ll need to set an `ORG_OVERRIDE` environment variable and set it to `catppuccin-rfc`. Without it, the cli will look for repos in the Catppuccin org.

**Comment by ohxxm** [comment]
I tried this but it doesn't fix the issue in the fish shell

**Comment by spookyintheam** [comment]
What error do you get on fish shell? I use fish shell too and it works perfectly for me. Can you post the error? 
```
./ctp search helix
Searching for packages:
helix
Found repo: helix
```

**Comment by Spaxly** [comment]
```
Documents/Code/Catppuccincli
❯ set ORG_OVERRIDE catppuccin-rfc

Documents/Code/Catppuccincli
❯ ./cli install helix
Installing packages...
helix
https://raw.githubusercontent.com/catppuccin/helix/main/.catppuccin.yaml
helix does not have a .catppuccin.yaml
Checking for installed packages:
```

**Comment by ohxxm** [comment]
Nvm, fixed the issue. I accidentally did set ORG_OVERRIDE catppuccin-rfc instead of export which fixed it.

**Comment by spookyintheam** [comment]
Okay since this is fixed, I'll close this issue.
